# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  default_contact_mailer: <%= ENV["DEFAULT_CONTACT_MAILER"] %>
  host: localhost
  iugu_account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>
  iugu_env: 'development'
  pubnub_channel: 'super_games_production'
  pubnub_publish: <%= ENV['PUBNUB_PUBLISH_KEY'] %>
  pubnub_subscribe: <%= ENV['PUBNUB_SUBSCRIBE_KEY'] %>
  pubnub_secret: <%= ENV['PUBNUB_SECRET_KEY'] %>
  realtime_private: <%= ENV['REALTIME_PRIVATE'] %>
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
  secret_key_base: 6717c8152039fac72880f4734066fb22dd968b188037b11c647fc4486608ecc2f3ee7a87ec99c9059500e7556ad9006f1b4334e1ced5fe13521326d3a9eb4022
  iugu_url: 'some-random-key'
  konduto_key: <%= ENV['KONDUTO_KEY'] %>
  konduto_public_key: <%= ENV['KONDUTO_PUBLIC_KEY'] %>

test:
  default_contact_mailer: <%= ENV["DEFAULT_CONTACT_MAILER"] %>
  host: localhost
  iugu_account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>
  iugu_url: 'some-random-key'
  konduto_public_key: <%= ENV['KONDUTO_PUBLIC_KEY'] %>
  konduto_key: <%= ENV['KONDUTO_KEY'] %>
  iugu_env: 'test'
  pubnub_channel: 'bugxdevelopment'
  pubnub_publish: <%= ENV['PUBNUB_PUBLISH_KEY'] %>
  pubnub_subscribe: <%= ENV['PUBNUB_SUBSCRIBE_KEY'] %>
  pubnub_secret: <%= ENV['PUBNUB_SECRET_KEY'] %>
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
  secret_key_base: fed3286f29a4919b12556a86ff06874aa138a1f34e8084395c1093e1126e557f217a6941cc0e473d9e0175387f7275e982a062c330018de3e5e30410fcbb1965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  aws_access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  default_contact_mailer: <%= ENV["DEFAULT_CONTACT_MAILER"] %>
  host: <%= ENV['HOST_URL'] %>
  iugu_account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>
  konduto_public_key: <%= ENV['KONDUTO_PUBLIC_KEY'] %>
  konduto_key: <%= ENV['KONDUTO_KEY'] %>
  iugu_url: <%= ENV['IUGU_URL_KEY'] %>
  iugu_env: <%= ENV['IUGU_ENV'] || ENV['RAILS_ENV'] %>
  pubnub_channel: <%= ENV['PUBNUB_CHANNEL'] %>
  pubnub_publish: <%= ENV['PUBNUB_PUBLISH_KEY'] %>
  pubnub_subscribe: <%= ENV['PUBNUB_SUBSCRIBE_KEY'] %>
  pubnub_secret: <%= ENV['PUBNUB_SECRET_KEY'] %>
  realtime_private: <%= ENV['REALTIME_PRIVATE'] %>
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
